<?php



/**
 * Implements hook_menu().
 */
function ats_log_call_menu() {
  $items = array();
  $items['ats-log-call'] = array(
    'title' => 'Статистика телефонных звонков',
    'description' => 'Позволяет просматрифать статистику звонков офисной АТС ГП "Укршахтгидрозащита".',
    'page callback' => 'ats_log_call_list',
    'access arguments' => TRUE,
    'weight' => -10,
  );

  return $items;
}



function ats_log_call_list() {
  $output = '';
  
  $select = db_select('ats_log_call','a')
  ->fields('a')
  ->orderBy('id', 'DESC')
  ->extend('PagerDefault')
  ->limit(30);
  $result = $select->execute();
  $rows = array();
  $i = 0;

/** Поскольку данніе в нашем случае попадают в базу непосредственно из мини-АТС
 *  будем считать их безопасными и не будем использовать построчную выборку 
 *  результатов с проверкой на "чистоту" 
 *
 * while ($row = $result->fetchAssoc()) {
 *   $rows[] = array_map('check_plain', (array) $row);
 * }
 */
  
  
  $rows = $result->fetchAll(PDO::FETCH_ASSOC);
  
  $stop = microtime(true);
  dpm($stop - $start,'Used seonds');
  $output .= theme('table', array( 'rows' => $rows));

  return $output;
}
