<?php



/**
 * Implements hook_menu().
 */
function ats_log_call_menu() {
  $items = array();
  $items['ats-log-call'] = array(
    'title' => 'Статистика телефонных звонков',
    'description' => 'Позволяет просматрифать статистику звонков офисной АТС ГП "Укршахтгидрозащита".',
    'page callback' => 'ats_log_call_list',
    'access arguments' => TRUE,
    'weight' => -10,
  );

  return $items;
}



function ats_log_call_list() {

$header = array(
  array('data' => 'ID звонка',     'field' => 'id'),
  array('data' => 'ID АТС', 'field' => 'ats_id'),
  array('data' => 'Дата звонка',           'field' => 'dates'),
  array('data' => 'Время звонка',           'field' => 'time'),
  array('data' => 'Ожидание ответа',           'field' => 'call_time_wait'),
  array('data' => 'Время развогвора',           'field' => 'call_time'),
  array('data' => 'Внутренний номер',           'field' => 'internal_number'),
  array('data' => 'Внешний номер',           'field' => 'external_number'),
  array('data' => 'Исходящяя линия',           'field' => 'external_line'),
  array('data' => 'Тип звонка',           'field' => 'type_call'),
);  

  $output = '';
  
  $select = db_select('ats_log_call','a')
  ->fields('a')
  ->orderBy('id', 'DESC')
  ->extend('PagerDefault')
  ->limit(30);
  $result = $select->execute();

/** Поскольку данніе в нашем случае попадают в базу непосредственно из мини-АТС
 *  будем считать их безопасными и не будем использовать построчную выборку 
 *  результатов с проверкой на "чистоту" 
 *
 * while ($row = $result->fetchAssoc()) {
 *   $rows[] = array_map('check_plain', (array) $row);
 * }
 */
  
  
  $rows = array();
  $rows = $result->fetchAll(PDO::FETCH_ASSOC);
  
  $output .= theme('table', array( 'header' => $header, 'rows' => $rows));
  $output .= theme('pager');
  return $output;
}
